### ISSUE TITLE
Documentation and examples?

### ISSUE THREAD

**Issue by Xsmael** [jumjum123/JUMFlot#14]
Hi.
Any Documentation and examples?

**Comment by jumjum123** [comment]
Hi,
yes, any

Am Mo., 8. Okt. 2018 um 09:52 Uhr schrieb Ismael OUEDRAOGO <
notifications@github.com>:

**Comment by Xsmael** [comment]
where can i find them ?

**Comment by jumjum123** [comment]
I cannot resist such a friendly and excessively polite request.

http://jumflot.jumware.com/IndexJUMFlot.html


Am Di., 9. Okt. 2018 um 10:49 Uhr schrieb Ismael OUEDRAOGO <
notifications@github.com>:

**Comment by Xsmael** [comment]
I don't know if this is sarcasm, but I'm sorry, I really didn't mean to be unpolite, was just asking...' because i couldn't find it in the readme.

Thanks.
